services:
  _defaults:
    public: true

  App\Service\CacheStore:
  App\Service\Definitions:
  App\Service\ExceptionHandler:
  App\Service\Translations:
  Symfony\Contracts\HttpClient\HttpClientInterface:
  Twig\Environment:
      public: true
