<?php

namespace App\Tests\Twig;

use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Twig\Environment;

class Base extends KernelTestCase
{
    protected Environment $twig;

    protected function setUp(): void
    {
        self::bootKernel();
        /** @var Environment $this->twig */
        $this->twig = static::getContainer()->get('twig');
    }

    protected function renderTemplate(string $template, array $context = []): string
    {
        return $this->twig->render($template, $context);
    }

    protected function assertExtendsBaseTemplate(string $template)
    {
        $this->assertStringContainsString('img src="/images/home_page_img.png"', $template);
        $this->assertStringContainsString('the a- dictionary', $template);
        $this->assertStringContainsString('src="/images/oxford_languages_logo.png"', $template);
        $this->assertStringContainsString('<script src="/js/homepage.js"></script>', $template);
    }

    protected function assertContentDefinitionsIndexTemplateIsRendered(string $template)
    {
        $this->assertStringContainsString('input type="text" id="search_word_definition" placeholder="Search"', $template);
        $this->assertStringContainsString('select id="select-definition-language" name="dict"', $template);
        $this->assertStringContainsString('<option value="en-gb" selected="selected">English: Definition</option>', $template);
        $this->assertStringContainsString('<option value="en-us">American: Definition</option>', $template);
        $this->assertStringContainsString('<option value="es">Spanish: Definition</option>', $template);
        $this->assertStringContainsString('<option value="fr">French: Definition</option>', $template);
        $this->assertStringContainsString('<option value="gu">Gujarati: Definition</option>', $template);
        $this->assertStringContainsString('<option value="hi">Hindi: Definition</option>', $template);
        $this->assertStringContainsString('<option value="lv">Latvian: Definition</option>', $template);
        $this->assertStringContainsString('<option value="ro">Romanian: Definition</option>', $template);
        $this->assertStringContainsString('<option value="ta">Tamil: Definition</option>', $template);
        $this->assertStringContainsString('<option value="zh">Chinese: Definition</option>', $template);
        $this->assertStringContainsString('href="#" class="js-search-definitions"', $template);
        $this->assertStringContainsString('src="/images/search_icon.png"', $template);
        $this->assertStringContainsString('<script src="/js/search_definitions.js"></script>', $template);

        $this->assertExtendsBaseTemplate($template);
    }

    protected function assertContentTranslationsIndexTemplateIsRendered(string $template)
    {
        $this->assertStringContainsString('input type="text" id="search_translations_word" placeholder="Search"', $template);
        $this->assertStringContainsString('select id="select-translations-languages" name="dict"', $template);
        $this->assertStringContainsString('<option disabled>-----English--------</option>', $template);
        $this->assertStringContainsString('<option value="en ar">English-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="en de">English-German</option>', $template);
        $this->assertStringContainsString('<option value="en el">English-Greek</option>', $template);
        $this->assertStringContainsString('<option value="en es">English-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="en fa">English-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="en ha">English-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="en hi">English-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="en id">English-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="en ig">English-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="en it" selected="selected">English-Italian</option>', $template);
        $this->assertStringContainsString('<option value="en ka">English-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="en mr">English-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="en ms">English-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="en pt">English-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="en qu">English-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="en ro">English-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="en ru">English-Russian</option>', $template);
        $this->assertStringContainsString('<option value="en tg">English-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="en tt">English-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="en yo">English-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="en zh">English-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----Arabic--------</option>', $template);
        $this->assertStringContainsString('<option value="ar en">Arabic-English</option>', $template);
        $this->assertStringContainsString('<option value="ar de">Arabic-German</option>', $template);
        $this->assertStringContainsString('<option value="ar el">Arabic-Greek</option>', $template);
        $this->assertStringContainsString('<option value="ar es">Arabic-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="ar fa">Arabic-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="ar ha">Arabic-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="ar hi">Arabic-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="ar id">Arabic-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="ar ig">Arabic-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="ar it">Arabic-Italian</option>', $template);
        $this->assertStringContainsString('<option value="ar ka">Arabic-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="ar mr">Arabic-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="ar ms">Arabic-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="ar pt">Arabic-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="ar qu">Arabic-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="ar ro">Arabic-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="ar ru">Arabic-Russian</option>', $template);
        $this->assertStringContainsString('<option value="ar tg">Arabic-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="ar tt">Arabic-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="ar yo">Arabic-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="ar zh">Arabic-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----German--------</option>', $template);
        $this->assertStringContainsString('<option value="de en">German-English</option>', $template);
        $this->assertStringContainsString('<option value="de ar">German-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="de el">German-Greek</option>', $template);
        $this->assertStringContainsString('<option value="de es">German-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="de fa">German-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="de ha">German-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="de hi">German-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="de id">German-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="de ig">German-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="de it">German-Italian</option>', $template);
        $this->assertStringContainsString('<option value="de ka">German-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="de mr">German-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="de ms">German-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="de pt">German-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="de qu">German-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="de ro">German-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="de ru">German-Russian</option>', $template);
        $this->assertStringContainsString('<option value="de tg">German-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="de tt">German-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="de yo">German-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="de zh">German-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----Greek--------</option>', $template);
        $this->assertStringContainsString('<option value="el en">Greek-English</option>', $template);
        $this->assertStringContainsString('<option value="el ar">Greek-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="el de">Greek-German</option>', $template);
        $this->assertStringContainsString('<option value="el es">Greek-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="el fa">Greek-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="el ha">Greek-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="el hi">Greek-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="el id">Greek-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="el ig">Greek-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="el it">Greek-Italian</option>', $template);
        $this->assertStringContainsString('<option value="el ka">Greek-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="el mr">Greek-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="el ms">Greek-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="el pt">Greek-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="el qu">Greek-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="el ro">Greek-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="el ru">Greek-Russian</option>', $template);
        $this->assertStringContainsString('<option value="el tg">Greek-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="el tt">Greek-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="el yo">Greek-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="el zh">Greek-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----Spanish--------</option>', $template);
        $this->assertStringContainsString('<option value="es en">Spanish-English</option>', $template);
        $this->assertStringContainsString('<option value="es ar">Spanish-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="es de">Spanish-German</option>', $template);
        $this->assertStringContainsString('<option value="es el">Spanish-Greek</option>', $template);
        $this->assertStringContainsString('<option value="es fa">Spanish-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="es ha">Spanish-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="es hi">Spanish-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="es id">Spanish-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="es ig">Spanish-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="es it">Spanish-Italian</option>', $template);
        $this->assertStringContainsString('<option value="es ka">Spanish-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="es mr">Spanish-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="es ms">Spanish-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="es pt">Spanish-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="es qu">Spanish-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="es ro">Spanish-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="es ru">Spanish-Russian</option>', $template);
        $this->assertStringContainsString('<option value="es tg">Spanish-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="es tt">Spanish-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="es yo">Spanish-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="es zh">Spanish-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----Hausa--------</option>', $template);
        $this->assertStringContainsString('<option value="ha en">Hausa-English</option>', $template);
        $this->assertStringContainsString('<option value="ha ar">Hausa-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="ha de">Hausa-German</option>', $template);
        $this->assertStringContainsString('<option value="ha el">Hausa-Greek</option>', $template);
        $this->assertStringContainsString('<option value="ha es">Hausa-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="ha fa">Hausa-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="ha hi">Hausa-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="ha id">Hausa-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="ha ig">Hausa-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="ha it">Hausa-Italian</option>', $template);
        $this->assertStringContainsString('<option value="ha ka">Hausa-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="ha mr">Hausa-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="ha ms">Hausa-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="ha pt">Hausa-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="ha qu">Hausa-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="ha ro">Hausa-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="ha ru">Hausa-Russian</option>', $template);
        $this->assertStringContainsString('<option value="ha tg">Hausa-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="ha tt">Hausa-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="ha yo">Hausa-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="ha zh">Hausa-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----Hindi--------</option>', $template);
        $this->assertStringContainsString('<option value="hi en">Hindi-English</option>', $template);
        $this->assertStringContainsString('<option value="hi ar">Hindi-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="hi de">Hindi-German</option>', $template);
        $this->assertStringContainsString('<option value="hi el">Hindi-Greek</option>', $template);
        $this->assertStringContainsString('<option value="hi es">Hindi-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="hi fa">Hindi-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="hi ha">Hindi-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="hi id">Hindi-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="hi ig">Hindi-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="hi it">Hindi-Italian</option>', $template);
        $this->assertStringContainsString('<option value="hi ka">Hindi-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="hi mr">Hindi-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="hi ms">Hindi-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="hi pt">Hindi-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="hi qu">Hindi-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="hi ro">Hindi-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="hi ru">Hindi-Russian</option>', $template);
        $this->assertStringContainsString('<option value="hi tg">Hindi-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="hi tt">Hindi-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="hi yo">Hindi-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="hi zh">Hindi-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----Indonesian--------</option>', $template);
        $this->assertStringContainsString('<option value="id en">Indonesian-English</option>', $template);
        $this->assertStringContainsString('<option value="id ar">Indonesian-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="id de">Indonesian-German</option>', $template);
        $this->assertStringContainsString('<option value="id el">Indonesian-Greek</option>', $template);
        $this->assertStringContainsString('<option value="id es">Indonesian-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="id fa">Indonesian-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="id ha">Indonesian-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="id hi">Indonesian-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="id ig">Indonesian-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="id it">Indonesian-Italian</option>', $template);
        $this->assertStringContainsString('<option value="id ka">Indonesian-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="id mr">Indonesian-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="id ms">Indonesian-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="id pt">Indonesian-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="id qu">Indonesian-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="id ro">Indonesian-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="id ru">Indonesian-Russian</option>', $template);
        $this->assertStringContainsString('<option value="id tg">Indonesian-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="id tt">Indonesian-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="id yo">Indonesian-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="id zh">Indonesian-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----Italian--------</option>', $template);
        $this->assertStringContainsString('<option value="it en">Italian-English</option>', $template);
        $this->assertStringContainsString('<option value="it ar">Italian-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="it de">Italian-German</option>', $template);
        $this->assertStringContainsString('<option value="it el">Italian-Greek</option>', $template);
        $this->assertStringContainsString('<option value="it es">Italian-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="it fa">Italian-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="it ha">Italian-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="it hi">Italian-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="it id">Italian-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="it ig">Italian-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="it ka">Italian-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="it mr">Italian-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="it ms">Italian-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="it pt">Italian-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="it qu">Italian-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="it ro">Italian-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="it ru">Italian-Russian</option>', $template);
        $this->assertStringContainsString('<option value="it tg">Italian-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="it tt">Italian-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="it yo">Italian-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="it zh">Italian-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----Marathi--------</option>', $template);
        $this->assertStringContainsString('<option value="mr en">Marathi-English</option>', $template);
        $this->assertStringContainsString('<option value="mr ar">Marathi-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="mr de">Marathi-German</option>', $template);
        $this->assertStringContainsString('<option value="mr el">Marathi-Greek</option>', $template);
        $this->assertStringContainsString('<option value="mr es">Marathi-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="mr fa">Marathi-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="mr ha">Marathi-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="mr hi">Marathi-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="mr id">Marathi-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="mr ig">Marathi-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="mr it">Marathi-Italian</option>', $template);
        $this->assertStringContainsString('<option value="mr ka">Marathi-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="mr ms">Marathi-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="mr pt">Marathi-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="mr qu">Marathi-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="mr ro">Marathi-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="mr ru">Marathi-Russian</option>', $template);
        $this->assertStringContainsString('<option value="mr tg">Marathi-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="mr tt">Marathi-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="mr yo">Marathi-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="mr zh">Marathi-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----Malaysian--------</option>', $template);
        $this->assertStringContainsString('<option value="ms en">Malaysian-English</option>', $template);
        $this->assertStringContainsString('<option value="ms ar">Malaysian-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="ms de">Malaysian-German</option>', $template);
        $this->assertStringContainsString('<option value="ms el">Malaysian-Greek</option>', $template);
        $this->assertStringContainsString('<option value="ms es">Malaysian-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="ms fa">Malaysian-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="ms ha">Malaysian-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="ms hi">Malaysian-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="ms id">Malaysian-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="ms ig">Malaysian-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="ms it">Malaysian-Italian</option>', $template);
        $this->assertStringContainsString('<option value="ms ka">Malaysian-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="ms mr">Malaysian-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="ms pt">Malaysian-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="ms qu">Malaysian-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="ms ro">Malaysian-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="ms ru">Malaysian-Russian</option>', $template);
        $this->assertStringContainsString('<option value="ms tg">Malaysian-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="ms tt">Malaysian-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="ms yo">Malaysian-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="ms zh">Malaysian-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----Portuguese--------</option>', $template);
        $this->assertStringContainsString('<option value="pt en">Portuguese-English</option>', $template);
        $this->assertStringContainsString('<option value="pt ar">Portuguese-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="pt de">Portuguese-German</option>', $template);
        $this->assertStringContainsString('<option value="pt el">Portuguese-Greek</option>', $template);
        $this->assertStringContainsString('<option value="pt es">Portuguese-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="pt fa">Portuguese-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="pt ha">Portuguese-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="pt hi">Portuguese-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="pt id">Portuguese-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="pt ig">Portuguese-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="pt it">Portuguese-Italian</option>', $template);
        $this->assertStringContainsString('<option value="pt ka">Portuguese-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="pt mr">Portuguese-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="pt ms">Portuguese-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="pt qu">Portuguese-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="pt ro">Portuguese-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="pt ru">Portuguese-Russian</option>', $template);
        $this->assertStringContainsString('<option value="pt tg">Portuguese-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="pt tt">Portuguese-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="pt yo">Portuguese-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="pt zh">Portuguese-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----Quechua--------</option>', $template);
        $this->assertStringContainsString('<option value="qu en">Quechua-English</option>', $template);
        $this->assertStringContainsString('<option value="qu ar">Quechua-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="qu de">Quechua-German</option>', $template);
        $this->assertStringContainsString('<option value="qu el">Quechua-Greek</option>', $template);
        $this->assertStringContainsString('<option value="qu es">Quechua-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="qu fa">Quechua-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="qu ha">Quechua-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="qu hi">Quechua-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="qu id">Quechua-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="qu ig">Quechua-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="qu it">Quechua-Italian</option>', $template);
        $this->assertStringContainsString('<option value="qu ka">Quechua-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="qu mr">Quechua-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="qu ms">Quechua-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="qu pt">Quechua-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="qu ro">Quechua-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="qu ru">Quechua-Russian</option>', $template);
        $this->assertStringContainsString('<option value="qu tg">Quechua-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="qu tt">Quechua-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="qu yo">Quechua-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="qu zh">Quechua-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----Russian--------</option>', $template);
        $this->assertStringContainsString('<option value="ru en">Russian-English</option>', $template);
        $this->assertStringContainsString('<option value="ru ar">Russian-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="ru de">Russian-German</option>', $template);
        $this->assertStringContainsString('<option value="ru el">Russian-Greek</option>', $template);
        $this->assertStringContainsString('<option value="ru es">Russian-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="ru fa">Russian-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="ru ha">Russian-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="ru hi">Russian-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="ru id">Russian-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="ru ig">Russian-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="ru it">Russian-Italian</option>', $template);
        $this->assertStringContainsString('<option value="ru ka">Russian-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="ru mr">Russian-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="ru ms">Russian-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="ru pt">Russian-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="ru qu">Russian-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="ru ro">Russian-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="ru tg">Russian-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="ru tt">Russian-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="ru yo">Russian-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="ru zh">Russian-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----Telugu--------</option>', $template);
        $this->assertStringContainsString('<option value="te en">Telugu-English</option>', $template);
        $this->assertStringContainsString('<option value="te ar">Telugu-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="te de">Telugu-German</option>', $template);
        $this->assertStringContainsString('<option value="te el">Telugu-Greek</option>', $template);
        $this->assertStringContainsString('<option value="te es">Telugu-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="te fa">Telugu-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="te ha">Telugu-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="te hi">Telugu-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="te id">Telugu-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="te ig">Telugu-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="te it">Telugu-Italian</option>', $template);
        $this->assertStringContainsString('<option value="te ka">Telugu-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="te mr">Telugu-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="te ms">Telugu-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="te pt">Telugu-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="te qu">Telugu-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="te ro">Telugu-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="te ru">Telugu-Russian</option>', $template);
        $this->assertStringContainsString('<option value="te tg">Telugu-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="te tt">Telugu-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="te yo">Telugu-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="te zh">Telugu-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----Tatar--------</option>', $template);
        $this->assertStringContainsString('<option value="tt en">Tatar-English</option>', $template);
        $this->assertStringContainsString('<option value="tt ar">Tatar-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="tt de">Tatar-German</option>', $template);
        $this->assertStringContainsString('<option value="tt el">Tatar-Greek</option>', $template);
        $this->assertStringContainsString('<option value="tt es">Tatar-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="tt fa">Tatar-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="tt ha">Tatar-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="tt hi">Tatar-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="tt id">Tatar-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="tt ig">Tatar-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="tt it">Tatar-Italian</option>', $template);
        $this->assertStringContainsString('<option value="tt ka">Tatar-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="tt mr">Tatar-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="tt ms">Tatar-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="tt pt">Tatar-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="tt qu">Tatar-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="tt ro">Tatar-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="tt ru">Tatar-Russian</option>', $template);
        $this->assertStringContainsString('<option value="tt tg">Tatar-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="tt yo">Tatar-Yoruba</option>', $template);
        $this->assertStringContainsString('<option value="tt zh">Tatar-Chinese</option>', $template);
        $this->assertStringContainsString('<option disabled>-----Chinese--------</option>', $template);
        $this->assertStringContainsString('<option value="zh en">Chinese-English</option>', $template);
        $this->assertStringContainsString('<option value="zh ar">Chinese-Arabic</option>', $template);
        $this->assertStringContainsString('<option value="zh de">Chinese-German</option>', $template);
        $this->assertStringContainsString('<option value="zh el">Chinese-Greek</option>', $template);
        $this->assertStringContainsString('<option value="zh es">Chinese-Spanish</option>', $template);
        $this->assertStringContainsString('<option value="zh fa">Chinese-Farsi</option>', $template);
        $this->assertStringContainsString('<option value="zh ha">Chinese-Hausa</option>', $template);
        $this->assertStringContainsString('<option value="zh hi">Chinese-Hindi</option>', $template);
        $this->assertStringContainsString('<option value="zh id">Chinese-Indonesian</option>', $template);
        $this->assertStringContainsString('<option value="zh ig">Chinese-Igbo</option>', $template);
        $this->assertStringContainsString('<option value="zh it">Chinese-Italian</option>', $template);
        $this->assertStringContainsString('<option value="zh ka">Chinese-Georgian</option>', $template);
        $this->assertStringContainsString('<option value="zh mr">Chinese-Marathi</option>', $template);
        $this->assertStringContainsString('<option value="zh ms">Chinese-Malaysian</option>', $template);
        $this->assertStringContainsString('<option value="zh pt">Chinese-Portuguese</option>', $template);
        $this->assertStringContainsString('<option value="zh qu">Chinese-Quechua</option>', $template);
        $this->assertStringContainsString('<option value="zh ro">Chinese-Romanian</option>', $template);
        $this->assertStringContainsString('<option value="zh ru">Chinese-Russian</option>', $template);
        $this->assertStringContainsString('<option value="zh tg">Chinese-Tajik</option>', $template);
        $this->assertStringContainsString('<option value="zh tt">Chinese-Tatar</option>', $template);
        $this->assertStringContainsString('<option value="zh yo">Chinese-Yoruba</option>', $template);
        $this->assertStringContainsString('href="#" class="js-search-translations"', $template);
        $this->assertStringContainsString('src="/images/search_icon.png"', $template);
        $this->assertStringContainsString('<script src="/js/search_translations.js"></script>', $template);

        $this->assertExtendsBaseTemplate($template);
    }
}
