<?php

namespace App\Tests\Twig;

use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Twig\Environment;

class Base extends KernelTestCase
{
    protected Environment $twig;

    protected function setUp(): void
    {
        self::bootKernel();
        /* @var Environment $this->twig */
        $this->twig = static::getContainer()->get('twig');
    }

    protected function renderTemplate(string $template, array $context = []): string
    {
        return $this->twig->render($template, $context);
    }

    protected function assertExtendsBaseTemplate(string $template)
    {
        $this->assertStringContainsString('<title>WordHop</title>', $template);
        $this->assertStringContainsString('<link rel="stylesheet" href="/css/app.css">', $template);
        $this->assertStringContainsString('<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css">', $template);
        $this->assertStringContainsString('<header class="app-header">', $template);
        $this->assertStringContainsString('<div class="brand">', $template);
        $this->assertStringContainsString('<img src="/images/dictionary_logo.png" height="300" alt="Logo" class="logo">', $template);
        $this->assertStringContainsString('<img src="/images/oxford_languages_logo.png" height="200" alt="Oxford Languages" class="oxford-logo">', $template);
        $this->assertStringContainsString('<nav class="search-bar">', $template);
        $this->assertStringContainsString('<input type="text" id="search_word" placeholder="Search for a word…" autocomplete="off">', $template);
        $this->assertStringContainsString('<select id="search_language">', $template);
        $this->assertStringContainsString('<main id="results-container">', $template);
        $this->assertStringContainsString('<button class="search-icon js-search-word" type="button">', $template);
        $this->assertStringContainsString('<img src="/images/search_icon.png" height="20" alt="Search">', $template);
        $this->assertStringContainsString('<button class="js-search-languages" data-mode="definitions">Definitions</button>', $template);
        $this->assertStringContainsString('<button class="js-search-languages" data-mode="translations">Translations</button>', $template);
        $this->assertStringContainsString('<ul id="suggestions"></ul>', $template);
        $this->assertStringContainsString('<footer class="site-footer" role="contentinfo">', $template);
        $this->assertStringContainsString('<div class="footer-inner">', $template);
        $this->assertStringContainsString('<div class="footer-brand">', $template);
        $this->assertStringContainsString('<span class="footer-logo">WordHop</span>', $template);
        $this->assertStringContainsString('<small class="footer-tag">Find meanings & translations fast.</small>', $template);
        $this->assertStringContainsString('<nav class="footer-links" aria-label="Footer">', $template);
        $this->assertStringContainsString('<a href="/">Home</a>', $template);
        $this->assertStringContainsString('<a href="/">Definitions</a>', $template);
        $this->assertStringContainsString('<a href="/translations">Translations</a>', $template);
        $this->assertStringContainsString('<div class="footer-meta">', $template);
        $this->assertStringContainsString('<span>v1.0.0</span>', $template);
        $this->assertStringContainsString('<span>© '.date('Y').' WordHop</span>', $template);
        $this->assertStringContainsString('<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>', $template);
        $this->assertStringContainsString('<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>', $template);
        $this->assertStringContainsString('<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>', $template);
        $this->assertStringContainsString('<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>', $template);
        $this->assertStringContainsString('<script type="module" src="/js/audio_controls.js"></script>', $template);
        $this->assertStringContainsString('<script type="module" src="/js/homepage.js"></script>', $template);
        $this->assertStringContainsString('<script type="module" src="/js/search_input.js"></script>', $template);
        $this->assertStringContainsString('<script type="module" src="/js/search_languages.js"></script>', $template);
    }

    protected function assertDefinitionsLanguagesAreRendered(string $template)
    {
        $this->assertStringContainsString('<option value="en-gb" selected>', $template);
        $this->assertStringContainsString('English', $template);
        $this->assertStringContainsString('<option value="en-us">', $template);
        $this->assertStringContainsString('American', $template);
        $this->assertStringContainsString('<option value="es">', $template);
        $this->assertStringContainsString('Spanish', $template);
        $this->assertStringContainsString('<option value="fr">', $template);
        $this->assertStringContainsString('French', $template);
        $this->assertStringContainsString('<option value="gu">', $template);
        $this->assertStringContainsString('Gujarati', $template);
        $this->assertStringContainsString('<option value="hi">', $template);
        $this->assertStringContainsString('Hindi', $template);
        $this->assertStringContainsString('<option value="lv">', $template);
        $this->assertStringContainsString('Latvian', $template);
        $this->assertStringContainsString('<option value="ro">', $template);
        $this->assertStringContainsString('Romanian', $template);
        $this->assertStringContainsString('<option value="ta">', $template);
        $this->assertStringContainsString('Tamil', $template);
        $this->assertStringContainsString('<option value="zh">', $template);
        $this->assertStringContainsString('Chinese', $template);
    }

    protected function assertTranslationsLanguagesAreRendered(string $template)
    {
        $this->assertStringContainsString('<optgroup label="English">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en ar"\s*>\s*English\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en de"\s*>\s*English\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en el"\s*>\s*English\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en es"\s*>\s*English\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en fa"\s*>\s*English\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en ha"\s*>\s*English\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en hi"\s*>\s*English\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en id"\s*>\s*English\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en ig"\s*>\s*English\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en it"[^>]*selected\s*>\s*English\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en ka"\s*>\s*English\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en mr"\s*>\s*English\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en ms"\s*>\s*English\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en pt"\s*>\s*English\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en qu"\s*>\s*English\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en ro"\s*>\s*English\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en ru"\s*>\s*English\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en tg"\s*>\s*English\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en tt"\s*>\s*English\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en yo"\s*>\s*English\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="en zh"\s*>\s*English\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="Arabic">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar en"\s*>\s*Arabic\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar de"\s*>\s*Arabic\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar el"\s*>\s*Arabic\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar es"\s*>\s*Arabic\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar fa"\s*>\s*Arabic\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar ha"\s*>\s*Arabic\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar hi"\s*>\s*Arabic\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar id"\s*>\s*Arabic\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar ig"\s*>\s*Arabic\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar it"\s*>\s*Arabic\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar ka"\s*>\s*Arabic\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar mr"\s*>\s*Arabic\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar ms"\s*>\s*Arabic\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar pt"\s*>\s*Arabic\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar qu"\s*>\s*Arabic\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar ro"\s*>\s*Arabic\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar ru"\s*>\s*Arabic\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar tg"\s*>\s*Arabic\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar tt"\s*>\s*Arabic\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar yo"\s*>\s*Arabic\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ar zh"\s*>\s*Arabic\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="German">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de en"\s*>\s*German\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de ar"\s*>\s*German\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de el"\s*>\s*German\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de es"\s*>\s*German\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de fa"\s*>\s*German\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de ha"\s*>\s*German\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de hi"\s*>\s*German\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de id"\s*>\s*German\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de ig"\s*>\s*German\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de it"\s*>\s*German\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de ka"\s*>\s*German\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de mr"\s*>\s*German\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de ms"\s*>\s*German\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de pt"\s*>\s*German\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de qu"\s*>\s*German\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de ro"\s*>\s*German\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de ru"\s*>\s*German\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de tg"\s*>\s*German\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de tt"\s*>\s*German\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de yo"\s*>\s*German\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="de zh"\s*>\s*German\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="Greek">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el en"\s*>\s*Greek\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el ar"\s*>\s*Greek\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el de"\s*>\s*Greek\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el es"\s*>\s*Greek\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el fa"\s*>\s*Greek\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el ha"\s*>\s*Greek\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el hi"\s*>\s*Greek\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el id"\s*>\s*Greek\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el ig"\s*>\s*Greek\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el it"\s*>\s*Greek\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el ka"\s*>\s*Greek\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el mr"\s*>\s*Greek\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el ms"\s*>\s*Greek\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el pt"\s*>\s*Greek\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el qu"\s*>\s*Greek\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el ro"\s*>\s*Greek\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el ru"\s*>\s*Greek\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el tg"\s*>\s*Greek\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el tt"\s*>\s*Greek\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el yo"\s*>\s*Greek\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="el zh"\s*>\s*Greek\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="Spanish">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es en"\s*>\s*Spanish\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es ar"\s*>\s*Spanish\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es de"\s*>\s*Spanish\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es el"\s*>\s*Spanish\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es fa"\s*>\s*Spanish\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es ha"\s*>\s*Spanish\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es hi"\s*>\s*Spanish\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es id"\s*>\s*Spanish\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es ig"\s*>\s*Spanish\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es it"\s*>\s*Spanish\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es ka"\s*>\s*Spanish\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es mr"\s*>\s*Spanish\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es ms"\s*>\s*Spanish\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es pt"\s*>\s*Spanish\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es qu"\s*>\s*Spanish\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es ro"\s*>\s*Spanish\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es ru"\s*>\s*Spanish\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es tg"\s*>\s*Spanish\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es tt"\s*>\s*Spanish\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es yo"\s*>\s*Spanish\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="es zh"\s*>\s*Spanish\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="Hausa">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha en"\s*>\s*Hausa\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha ar"\s*>\s*Hausa\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha de"\s*>\s*Hausa\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha el"\s*>\s*Hausa\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha es"\s*>\s*Hausa\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha fa"\s*>\s*Hausa\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha hi"\s*>\s*Hausa\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha id"\s*>\s*Hausa\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha ig"\s*>\s*Hausa\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha it"\s*>\s*Hausa\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha ka"\s*>\s*Hausa\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha mr"\s*>\s*Hausa\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha ms"\s*>\s*Hausa\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha pt"\s*>\s*Hausa\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha qu"\s*>\s*Hausa\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha ro"\s*>\s*Hausa\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha ru"\s*>\s*Hausa\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha tg"\s*>\s*Hausa\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha tt"\s*>\s*Hausa\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha yo"\s*>\s*Hausa\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ha zh"\s*>\s*Hausa\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="Hindi">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi en"\s*>\s*Hindi\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi ar"\s*>\s*Hindi\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi de"\s*>\s*Hindi\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi el"\s*>\s*Hindi\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi es"\s*>\s*Hindi\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi fa"\s*>\s*Hindi\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi ha"\s*>\s*Hindi\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi id"\s*>\s*Hindi\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi ig"\s*>\s*Hindi\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi it"\s*>\s*Hindi\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi ka"\s*>\s*Hindi\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi mr"\s*>\s*Hindi\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi ms"\s*>\s*Hindi\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi pt"\s*>\s*Hindi\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi qu"\s*>\s*Hindi\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi ro"\s*>\s*Hindi\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi ru"\s*>\s*Hindi\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi tg"\s*>\s*Hindi\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi tt"\s*>\s*Hindi\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi yo"\s*>\s*Hindi\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="hi zh"\s*>\s*Hindi\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="Indonesian">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id en"\s*>\s*Indonesian\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id ar"\s*>\s*Indonesian\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id de"\s*>\s*Indonesian\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id el"\s*>\s*Indonesian\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id es"\s*>\s*Indonesian\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id fa"\s*>\s*Indonesian\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id ha"\s*>\s*Indonesian\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id hi"\s*>\s*Indonesian\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id ig"\s*>\s*Indonesian\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id it"\s*>\s*Indonesian\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id ka"\s*>\s*Indonesian\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id mr"\s*>\s*Indonesian\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id ms"\s*>\s*Indonesian\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id pt"\s*>\s*Indonesian\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id qu"\s*>\s*Indonesian\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id ro"\s*>\s*Indonesian\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id ru"\s*>\s*Indonesian\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id tg"\s*>\s*Indonesian\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id tt"\s*>\s*Indonesian\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id yo"\s*>\s*Indonesian\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="id zh"\s*>\s*Indonesian\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="Italian">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it en"\s*>\s*Italian\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it ar"\s*>\s*Italian\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it de"\s*>\s*Italian\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it el"\s*>\s*Italian\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it es"\s*>\s*Italian\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it fa"\s*>\s*Italian\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it ha"\s*>\s*Italian\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it hi"\s*>\s*Italian\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it id"\s*>\s*Italian\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it ig"\s*>\s*Italian\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it ka"\s*>\s*Italian\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it mr"\s*>\s*Italian\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it ms"\s*>\s*Italian\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it pt"\s*>\s*Italian\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it qu"\s*>\s*Italian\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it ro"\s*>\s*Italian\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it ru"\s*>\s*Italian\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it tg"\s*>\s*Italian\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it tt"\s*>\s*Italian\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it yo"\s*>\s*Italian\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="it zh"\s*>\s*Italian\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="Marathi">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr en"\s*>\s*Marathi\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr ar"\s*>\s*Marathi\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr de"\s*>\s*Marathi\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr el"\s*>\s*Marathi\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr es"\s*>\s*Marathi\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr fa"\s*>\s*Marathi\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr ha"\s*>\s*Marathi\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr hi"\s*>\s*Marathi\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr id"\s*>\s*Marathi\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr ig"\s*>\s*Marathi\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr it"\s*>\s*Marathi\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr ka"\s*>\s*Marathi\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr ms"\s*>\s*Marathi\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr pt"\s*>\s*Marathi\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr qu"\s*>\s*Marathi\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr ro"\s*>\s*Marathi\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr ru"\s*>\s*Marathi\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr tg"\s*>\s*Marathi\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr tt"\s*>\s*Marathi\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr yo"\s*>\s*Marathi\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="mr zh"\s*>\s*Marathi\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="Malaysian">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms en"\s*>\s*Malaysian\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms ar"\s*>\s*Malaysian\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms de"\s*>\s*Malaysian\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms el"\s*>\s*Malaysian\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms es"\s*>\s*Malaysian\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms fa"\s*>\s*Malaysian\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms ha"\s*>\s*Malaysian\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms hi"\s*>\s*Malaysian\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms id"\s*>\s*Malaysian\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms ig"\s*>\s*Malaysian\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms it"\s*>\s*Malaysian\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms ka"\s*>\s*Malaysian\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms mr"\s*>\s*Malaysian\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms pt"\s*>\s*Malaysian\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms qu"\s*>\s*Malaysian\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms ro"\s*>\s*Malaysian\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms ru"\s*>\s*Malaysian\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms tg"\s*>\s*Malaysian\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms tt"\s*>\s*Malaysian\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms yo"\s*>\s*Malaysian\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ms zh"\s*>\s*Malaysian\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="Portuguese">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt en"\s*>\s*Portuguese\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt ar"\s*>\s*Portuguese\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt de"\s*>\s*Portuguese\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt el"\s*>\s*Portuguese\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt es"\s*>\s*Portuguese\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt fa"\s*>\s*Portuguese\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt ha"\s*>\s*Portuguese\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt hi"\s*>\s*Portuguese\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt id"\s*>\s*Portuguese\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt ig"\s*>\s*Portuguese\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt it"\s*>\s*Portuguese\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt ka"\s*>\s*Portuguese\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt mr"\s*>\s*Portuguese\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt ms"\s*>\s*Portuguese\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt qu"\s*>\s*Portuguese\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt ro"\s*>\s*Portuguese\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt ru"\s*>\s*Portuguese\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt tg"\s*>\s*Portuguese\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt tt"\s*>\s*Portuguese\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt yo"\s*>\s*Portuguese\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="pt zh"\s*>\s*Portuguese\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="Quechua">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu en"\s*>\s*Quechua\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu ar"\s*>\s*Quechua\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu de"\s*>\s*Quechua\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu el"\s*>\s*Quechua\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu es"\s*>\s*Quechua\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu fa"\s*>\s*Quechua\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu ha"\s*>\s*Quechua\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu hi"\s*>\s*Quechua\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu id"\s*>\s*Quechua\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu ig"\s*>\s*Quechua\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu it"\s*>\s*Quechua\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu ka"\s*>\s*Quechua\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu mr"\s*>\s*Quechua\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu ms"\s*>\s*Quechua\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu pt"\s*>\s*Quechua\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu ro"\s*>\s*Quechua\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu ru"\s*>\s*Quechua\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu tg"\s*>\s*Quechua\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu tt"\s*>\s*Quechua\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu yo"\s*>\s*Quechua\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="qu zh"\s*>\s*Quechua\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="Russian">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru en"\s*>\s*Russian\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru ar"\s*>\s*Russian\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru de"\s*>\s*Russian\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru el"\s*>\s*Russian\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru es"\s*>\s*Russian\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru fa"\s*>\s*Russian\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru ha"\s*>\s*Russian\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru hi"\s*>\s*Russian\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru id"\s*>\s*Russian\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru ig"\s*>\s*Russian\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru it"\s*>\s*Russian\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru ka"\s*>\s*Russian\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru mr"\s*>\s*Russian\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru ms"\s*>\s*Russian\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru pt"\s*>\s*Russian\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru qu"\s*>\s*Russian\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru ro"\s*>\s*Russian\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru tg"\s*>\s*Russian\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru tt"\s*>\s*Russian\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru yo"\s*>\s*Russian\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="ru zh"\s*>\s*Russian\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="Telugu">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te en"\s*>\s*Telugu\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te ar"\s*>\s*Telugu\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te de"\s*>\s*Telugu\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te el"\s*>\s*Telugu\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te es"\s*>\s*Telugu\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te fa"\s*>\s*Telugu\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te ha"\s*>\s*Telugu\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te hi"\s*>\s*Telugu\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te id"\s*>\s*Telugu\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te ig"\s*>\s*Telugu\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te it"\s*>\s*Telugu\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te ka"\s*>\s*Telugu\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te mr"\s*>\s*Telugu\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te ms"\s*>\s*Telugu\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te pt"\s*>\s*Telugu\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te qu"\s*>\s*Telugu\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te ro"\s*>\s*Telugu\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te ru"\s*>\s*Telugu\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te tg"\s*>\s*Telugu\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te tt"\s*>\s*Telugu\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te yo"\s*>\s*Telugu\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="te zh"\s*>\s*Telugu\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="Tatar">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt en"\s*>\s*Tatar\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt ar"\s*>\s*Tatar\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt de"\s*>\s*Tatar\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt el"\s*>\s*Tatar\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt es"\s*>\s*Tatar\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt fa"\s*>\s*Tatar\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt ha"\s*>\s*Tatar\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt hi"\s*>\s*Tatar\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt id"\s*>\s*Tatar\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt ig"\s*>\s*Tatar\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt it"\s*>\s*Tatar\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt ka"\s*>\s*Tatar\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt mr"\s*>\s*Tatar\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt ms"\s*>\s*Tatar\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt pt"\s*>\s*Tatar\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt qu"\s*>\s*Tatar\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt ro"\s*>\s*Tatar\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt ru"\s*>\s*Tatar\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt tg"\s*>\s*Tatar\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt yo"\s*>\s*Tatar\s*→\s*Yoruba\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="tt zh"\s*>\s*Tatar\s*→\s*Chinese\s*<\/option>/s', $template);
        $this->assertStringContainsString('<optgroup label="Chinese">', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh en"\s*>\s*Chinese\s*→\s*English\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh ar"\s*>\s*Chinese\s*→\s*Arabic\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh de"\s*>\s*Chinese\s*→\s*German\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh el"\s*>\s*Chinese\s*→\s*Greek\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh es"\s*>\s*Chinese\s*→\s*Spanish\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh fa"\s*>\s*Chinese\s*→\s*Farsi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh ha"\s*>\s*Chinese\s*→\s*Hausa\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh hi"\s*>\s*Chinese\s*→\s*Hindi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh id"\s*>\s*Chinese\s*→\s*Indonesian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh ig"\s*>\s*Chinese\s*→\s*Igbo\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh it"\s*>\s*Chinese\s*→\s*Italian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh ka"\s*>\s*Chinese\s*→\s*Georgian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh mr"\s*>\s*Chinese\s*→\s*Marathi\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh ms"\s*>\s*Chinese\s*→\s*Malaysian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh pt"\s*>\s*Chinese\s*→\s*Portuguese\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh qu"\s*>\s*Chinese\s*→\s*Quechua\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh ro"\s*>\s*Chinese\s*→\s*Romanian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh ru"\s*>\s*Chinese\s*→\s*Russian\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh tg"\s*>\s*Chinese\s*→\s*Tajik\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh tt"\s*>\s*Chinese\s*→\s*Tatar\s*<\/option>/s', $template);
        $this->assertMatchesRegularExpression('/<option\s+value="zh yo"\s*>\s*Chinese\s*→\s*Yoruba\s*<\/option>/s', $template);
    }
}
