<?php

namespace App\Tests\Twig;

use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Twig\Environment;

class Base extends KernelTestCase
{
    protected Environment $twig;

    protected function setUp(): void
    {
        self::bootKernel();
        /** @var Environment $this->twig */
        $this->twig = static::getContainer()->get('twig');
    }

    protected function renderTemplate(string $template, array $context = []): string
    {
        return $this->twig->render($template, $context);
    }

    protected function assertExtendsBaseTemplate(string $template)
    {
        $this->assertStringContainsString('<title>WordHop</title>', $template);
        $this->assertStringContainsString('<link rel="stylesheet" href="/css/app.css">', $template);
        $this->assertStringContainsString('<header class="app-header">', $template);
        $this->assertStringContainsString('<div class="brand">', $template);
        $this->assertStringContainsString('<img src="/images/dictionary_logo.png" height="300" alt="Logo" class="logo">', $template);
        $this->assertStringContainsString('<img src="/images/oxford_languages_logo.png" height="200" alt="Oxford Languages" class="oxford-logo">', $template);
        $this->assertStringContainsString('<nav class="search-bar">', $template);
        $this->assertStringContainsString('<input type="text" id="search_word" placeholder="Search for a word…" autocomplete="off">', $template);
        $this->assertStringContainsString('<select id="search_language">', $template);
        $this->assertStringContainsString('<main id="results-container">', $template);
        $this->assertStringContainsString('<button class="search-icon js-search-word" type="button">', $template);
        $this->assertStringContainsString('<img src="/images/search_icon.png" height="20" alt="Search">', $template);
        $this->assertStringContainsString('<button class="js-search-languages" data-mode="definitions">Definitions</button>', $template);
        $this->assertStringContainsString('<button class="js-search-languages" data-mode="translations">Translations</button>', $template);
        $this->assertStringContainsString('<ul id="suggestions"></ul>', $template);
        $this->assertStringContainsString('<footer class="site-footer" role="contentinfo">', $template);
        $this->assertStringContainsString('<div class="footer-inner">', $template);
        $this->assertStringContainsString('<div class="footer-brand">', $template);
        $this->assertStringContainsString('<span class="footer-logo">WordHop</span>', $template);
        $this->assertStringContainsString('<small class="footer-tag">Find meanings & translations fast.</small>', $template);
        $this->assertStringContainsString('<nav class="footer-links" aria-label="Footer">', $template);
        $this->assertStringContainsString('<a href="/">Home</a>', $template);
        $this->assertStringContainsString('<a href="/">Definitions</a>', $template);
        $this->assertStringContainsString('<a href="/translations">Translations</a>', $template);
        $this->assertStringContainsString('<div class="footer-meta">', $template);
        $this->assertStringContainsString('<span>v1.0.0</span>', $template);
        $this->assertStringContainsString('<span>© ' . date('Y') . ' WordHop</span>', $template);
        $this->assertStringContainsString('<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>', $template);
        $this->assertStringContainsString('<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>', $template);
        $this->assertStringContainsString('<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>', $template);
        $this->assertStringContainsString('<script type="module" src="/js/audio_controls.js"></script>', $template);
        $this->assertStringContainsString('<script type="module" src="/js/homepage.js"></script>', $template);
        $this->assertStringContainsString('<script type="module" src="/js/search_input.js"></script>', $template);
        $this->assertStringContainsString('<script type="module" src="/js/search_languages.js"></script>', $template);
    }

    protected function assertDefinitionsLanguagesAreRendered(string $template)
    {
        $this->assertStringContainsString('<option value="en-gb" selected>', $template);
        $this->assertStringContainsString('English', $template);
        $this->assertStringContainsString('<option value="en-us">', $template);
        $this->assertStringContainsString('American', $template);
        $this->assertStringContainsString('<option value="es">', $template);
        $this->assertStringContainsString('Spanish', $template);
        $this->assertStringContainsString('<option value="fr">', $template);
        $this->assertStringContainsString('French', $template);
        $this->assertStringContainsString('<option value="gu">', $template);
        $this->assertStringContainsString('Gujarati', $template);
        $this->assertStringContainsString('<option value="hi">', $template);
        $this->assertStringContainsString('Hindi', $template);
        $this->assertStringContainsString('<option value="lv">', $template);
        $this->assertStringContainsString('Latvian', $template);
        $this->assertStringContainsString('<option value="ro">', $template);
        $this->assertStringContainsString('Romanian', $template);
        $this->assertStringContainsString('<option value="ta">', $template);
        $this->assertStringContainsString('Tamil', $template);
        $this->assertStringContainsString('<option value="zh">', $template);
        $this->assertStringContainsString('Chinese', $template);
    }

    protected function assertTranslationsLanguagesAreRendered(string $template)
    {
        $this->assertStringContainsString('<option disabled>--------English--------</option>', $template);
        $this->assertStringContainsString('<option value="en ar">', $template);
        $this->assertStringContainsString('English-Arabic', $template);
        $this->assertStringContainsString('<option value="en de">', $template);
        $this->assertStringContainsString('English-German', $template);
        $this->assertStringContainsString('<option value="en el">', $template);
        $this->assertStringContainsString('English-Greek', $template);
        $this->assertStringContainsString('<option value="en es">', $template);
        $this->assertStringContainsString('English-Spanish', $template);
        $this->assertStringContainsString('<option value="en fa">', $template);
        $this->assertStringContainsString('English-Farsi', $template);
        $this->assertStringContainsString('<option value="en ha">', $template);
        $this->assertStringContainsString('English-Hausa', $template);
        $this->assertStringContainsString('<option value="en hi">', $template);
        $this->assertStringContainsString('English-Hindi', $template);
        $this->assertStringContainsString('<option value="en id">', $template);
        $this->assertStringContainsString('English-Indonesian', $template);
        $this->assertStringContainsString('<option value="en ig">', $template);
        $this->assertStringContainsString('English-Igbo', $template);
        $this->assertStringContainsString('<option value="en it" selected>', $template);
        $this->assertStringContainsString('English-Italian', $template);
        $this->assertStringContainsString('<option value="en ka">', $template);
        $this->assertStringContainsString('English-Georgian', $template);
        $this->assertStringContainsString('<option value="en mr">', $template);
        $this->assertStringContainsString('English-Marathi', $template);
        $this->assertStringContainsString('<option value="en ms">', $template);
        $this->assertStringContainsString('English-Malaysian', $template);
        $this->assertStringContainsString('<option value="en pt">', $template);
        $this->assertStringContainsString('English-Portuguese', $template);
        $this->assertStringContainsString('<option value="en qu">', $template);
        $this->assertStringContainsString('English-Quechua', $template);
        $this->assertStringContainsString('<option value="en ro">', $template);
        $this->assertStringContainsString('English-Romanian', $template);
        $this->assertStringContainsString('<option value="en ru">', $template);
        $this->assertStringContainsString('English-Russian', $template);
        $this->assertStringContainsString('<option value="en tg">', $template);
        $this->assertStringContainsString('English-Tajik', $template);
        $this->assertStringContainsString('<option value="en tt">', $template);
        $this->assertStringContainsString('English-Tatar', $template);
        $this->assertStringContainsString('<option value="en yo">', $template);
        $this->assertStringContainsString('English-Yoruba', $template);
        $this->assertStringContainsString('<option value="en zh">', $template);
        $this->assertStringContainsString('English-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------Arabic--------</option>', $template);
        $this->assertStringContainsString('<option value="ar en">', $template);
        $this->assertStringContainsString('Arabic-English', $template);
        $this->assertStringContainsString('<option value="ar de">', $template);
        $this->assertStringContainsString('Arabic-German', $template);
        $this->assertStringContainsString('<option value="ar el">', $template);
        $this->assertStringContainsString('Arabic-Greek', $template);
        $this->assertStringContainsString('<option value="ar es">', $template);
        $this->assertStringContainsString('Arabic-Spanish', $template);
        $this->assertStringContainsString('<option value="ar fa">', $template);
        $this->assertStringContainsString('Arabic-Farsi', $template);
        $this->assertStringContainsString('<option value="ar ha">', $template);
        $this->assertStringContainsString('Arabic-Hausa', $template);
        $this->assertStringContainsString('<option value="ar hi">', $template);
        $this->assertStringContainsString('Arabic-Hindi', $template);
        $this->assertStringContainsString('<option value="ar id">', $template);
        $this->assertStringContainsString('Arabic-Indonesian', $template);
        $this->assertStringContainsString('<option value="ar ig">', $template);
        $this->assertStringContainsString('Arabic-Igbo', $template);
        $this->assertStringContainsString('<option value="ar it">', $template);
        $this->assertStringContainsString('Arabic-Italian', $template);
        $this->assertStringContainsString('<option value="ar ka">', $template);
        $this->assertStringContainsString('Arabic-Georgian', $template);
        $this->assertStringContainsString('<option value="ar mr">', $template);
        $this->assertStringContainsString('Arabic-Marathi', $template);
        $this->assertStringContainsString('<option value="ar ms">', $template);
        $this->assertStringContainsString('Arabic-Malaysian', $template);
        $this->assertStringContainsString('<option value="ar pt">', $template);
        $this->assertStringContainsString('Arabic-Portuguese', $template);
        $this->assertStringContainsString('<option value="ar qu">', $template);
        $this->assertStringContainsString('Arabic-Quechua', $template);
        $this->assertStringContainsString('<option value="ar ro">', $template);
        $this->assertStringContainsString('Arabic-Romanian', $template);
        $this->assertStringContainsString('<option value="ar ru">', $template);
        $this->assertStringContainsString('Arabic-Russian', $template);
        $this->assertStringContainsString('<option value="ar tg">', $template);
        $this->assertStringContainsString('Arabic-Tajik', $template);
        $this->assertStringContainsString('<option value="ar tt">', $template);
        $this->assertStringContainsString('Arabic-Tatar', $template);
        $this->assertStringContainsString('<option value="ar yo">', $template);
        $this->assertStringContainsString('Arabic-Yoruba', $template);
        $this->assertStringContainsString('<option value="ar zh">', $template);
        $this->assertStringContainsString('Arabic-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------German--------</option>', $template);
        $this->assertStringContainsString('<option value="de en">', $template);
        $this->assertStringContainsString('German-English', $template);
        $this->assertStringContainsString('<option value="de ar">', $template);
        $this->assertStringContainsString('German-Arabic', $template);
        $this->assertStringContainsString('<option value="de el">', $template);
        $this->assertStringContainsString('German-Greek', $template);
        $this->assertStringContainsString('<option value="de es">', $template);
        $this->assertStringContainsString('German-Spanish', $template);
        $this->assertStringContainsString('<option value="de fa">', $template);
        $this->assertStringContainsString('German-Farsi', $template);
        $this->assertStringContainsString('<option value="de ha">', $template);
        $this->assertStringContainsString('German-Hausa', $template);
        $this->assertStringContainsString('<option value="de hi">', $template);
        $this->assertStringContainsString('German-Hindi', $template);
        $this->assertStringContainsString('<option value="de id">', $template);
        $this->assertStringContainsString('German-Indonesian', $template);
        $this->assertStringContainsString('<option value="de ig">', $template);
        $this->assertStringContainsString('German-Igbo', $template);
        $this->assertStringContainsString('<option value="de it">', $template);
        $this->assertStringContainsString('German-Italian', $template);
        $this->assertStringContainsString('<option value="de ka">', $template);
        $this->assertStringContainsString('German-Georgian', $template);
        $this->assertStringContainsString('<option value="de mr">', $template);
        $this->assertStringContainsString('German-Marathi', $template);
        $this->assertStringContainsString('<option value="de ms">', $template);
        $this->assertStringContainsString('German-Malaysian', $template);
        $this->assertStringContainsString('<option value="de pt">', $template);
        $this->assertStringContainsString('German-Portuguese', $template);
        $this->assertStringContainsString('<option value="de qu">', $template);
        $this->assertStringContainsString('German-Quechua', $template);
        $this->assertStringContainsString('<option value="de ro">', $template);
        $this->assertStringContainsString('German-Romanian', $template);
        $this->assertStringContainsString('<option value="de ru">', $template);
        $this->assertStringContainsString('German-Russian', $template);
        $this->assertStringContainsString('<option value="de tg">', $template);
        $this->assertStringContainsString('German-Tajik', $template);
        $this->assertStringContainsString('<option value="de tt">', $template);
        $this->assertStringContainsString('German-Tatar', $template);
        $this->assertStringContainsString('<option value="de yo">', $template);
        $this->assertStringContainsString('German-Yoruba', $template);
        $this->assertStringContainsString('<option value="de zh">', $template);
        $this->assertStringContainsString('German-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------Greek--------</option>', $template);
        $this->assertStringContainsString('<option value="el en">', $template);
        $this->assertStringContainsString('Greek-English', $template);
        $this->assertStringContainsString('<option value="el ar">', $template);
        $this->assertStringContainsString('Greek-Arabic', $template);
        $this->assertStringContainsString('<option value="el de">', $template);
        $this->assertStringContainsString('Greek-German', $template);
        $this->assertStringContainsString('<option value="el es">', $template);
        $this->assertStringContainsString('Greek-Spanish', $template);
        $this->assertStringContainsString('<option value="el fa">', $template);
        $this->assertStringContainsString('Greek-Farsi', $template);
        $this->assertStringContainsString('<option value="el ha">', $template);
        $this->assertStringContainsString('Greek-Hausa', $template);
        $this->assertStringContainsString('<option value="el hi">', $template);
        $this->assertStringContainsString('Greek-Hindi', $template);
        $this->assertStringContainsString('<option value="el id">', $template);
        $this->assertStringContainsString('Greek-Indonesian', $template);
        $this->assertStringContainsString('<option value="el ig">', $template);
        $this->assertStringContainsString('Greek-Igbo', $template);
        $this->assertStringContainsString('<option value="el it">', $template);
        $this->assertStringContainsString('Greek-Italian', $template);
        $this->assertStringContainsString('<option value="el ka">', $template);
        $this->assertStringContainsString('Greek-Georgian', $template);
        $this->assertStringContainsString('<option value="el mr">', $template);
        $this->assertStringContainsString('Greek-Marathi', $template);
        $this->assertStringContainsString('<option value="el ms">', $template);
        $this->assertStringContainsString('Greek-Malaysian', $template);
        $this->assertStringContainsString('<option value="el pt">', $template);
        $this->assertStringContainsString('Greek-Portuguese', $template);
        $this->assertStringContainsString('<option value="el qu">', $template);
        $this->assertStringContainsString('Greek-Quechua', $template);
        $this->assertStringContainsString('<option value="el ro">', $template);
        $this->assertStringContainsString('Greek-Romanian', $template);
        $this->assertStringContainsString('<option value="el ru">', $template);
        $this->assertStringContainsString('Greek-Russian', $template);
        $this->assertStringContainsString('<option value="el tg">', $template);
        $this->assertStringContainsString('Greek-Tajik', $template);
        $this->assertStringContainsString('<option value="el tt">', $template);
        $this->assertStringContainsString('Greek-Tatar', $template);
        $this->assertStringContainsString('<option value="el yo">', $template);
        $this->assertStringContainsString('Greek-Yoruba', $template);
        $this->assertStringContainsString('<option value="el zh">', $template);
        $this->assertStringContainsString('Greek-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------Spanish--------</option>', $template);
        $this->assertStringContainsString('<option value="es en">', $template);
        $this->assertStringContainsString('Spanish-English', $template);
        $this->assertStringContainsString('<option value="es ar">', $template);
        $this->assertStringContainsString('Spanish-Arabic', $template);
        $this->assertStringContainsString('<option value="es de">', $template);
        $this->assertStringContainsString('Spanish-German', $template);
        $this->assertStringContainsString('<option value="es el">', $template);
        $this->assertStringContainsString('Spanish-Greek', $template);
        $this->assertStringContainsString('<option value="es fa">', $template);
        $this->assertStringContainsString('Spanish-Farsi', $template);
        $this->assertStringContainsString('<option value="es ha">', $template);
        $this->assertStringContainsString('Spanish-Hausa', $template);
        $this->assertStringContainsString('<option value="es hi">', $template);
        $this->assertStringContainsString('Spanish-Hindi', $template);
        $this->assertStringContainsString('<option value="es id">', $template);
        $this->assertStringContainsString('Spanish-Indonesian', $template);
        $this->assertStringContainsString('<option value="es ig">', $template);
        $this->assertStringContainsString('Spanish-Igbo', $template);
        $this->assertStringContainsString('<option value="es it">', $template);
        $this->assertStringContainsString('Spanish-Italian', $template);
        $this->assertStringContainsString('<option value="es ka">', $template);
        $this->assertStringContainsString('Spanish-Georgian', $template);
        $this->assertStringContainsString('<option value="es mr">', $template);
        $this->assertStringContainsString('Spanish-Marathi', $template);
        $this->assertStringContainsString('<option value="es ms">', $template);
        $this->assertStringContainsString('Spanish-Malaysian', $template);
        $this->assertStringContainsString('<option value="es pt">', $template);
        $this->assertStringContainsString('Spanish-Portuguese', $template);
        $this->assertStringContainsString('<option value="es qu">', $template);
        $this->assertStringContainsString('Spanish-Quechua', $template);
        $this->assertStringContainsString('<option value="es ro">', $template);
        $this->assertStringContainsString('Spanish-Romanian', $template);
        $this->assertStringContainsString('<option value="es ru">', $template);
        $this->assertStringContainsString('Spanish-Russian', $template);
        $this->assertStringContainsString('<option value="es tg">', $template);
        $this->assertStringContainsString('Spanish-Tajik', $template);
        $this->assertStringContainsString('<option value="es tt">', $template);
        $this->assertStringContainsString('Spanish-Tatar', $template);
        $this->assertStringContainsString('<option value="es yo">', $template);
        $this->assertStringContainsString('Spanish-Yoruba', $template);
        $this->assertStringContainsString('<option value="es zh">', $template);
        $this->assertStringContainsString('Spanish-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------Hausa--------</option>', $template);
        $this->assertStringContainsString('<option value="ha en">', $template);
        $this->assertStringContainsString('Hausa-English', $template);
        $this->assertStringContainsString('<option value="ha ar">', $template);
        $this->assertStringContainsString('Hausa-Arabic', $template);
        $this->assertStringContainsString('<option value="ha de">', $template);
        $this->assertStringContainsString('Hausa-German', $template);
        $this->assertStringContainsString('<option value="ha el">', $template);
        $this->assertStringContainsString('Hausa-Greek', $template);
        $this->assertStringContainsString('<option value="ha es">', $template);
        $this->assertStringContainsString('Hausa-Spanish', $template);
        $this->assertStringContainsString('<option value="ha fa">', $template);
        $this->assertStringContainsString('Hausa-Farsi', $template);
        $this->assertStringContainsString('<option value="ha hi">', $template);
        $this->assertStringContainsString('Hausa-Hindi', $template);
        $this->assertStringContainsString('<option value="ha id">', $template);
        $this->assertStringContainsString('Hausa-Indonesian', $template);
        $this->assertStringContainsString('<option value="ha ig">', $template);
        $this->assertStringContainsString('Hausa-Igbo', $template);
        $this->assertStringContainsString('<option value="ha it">', $template);
        $this->assertStringContainsString('Hausa-Italian', $template);
        $this->assertStringContainsString('<option value="ha ka">', $template);
        $this->assertStringContainsString('Hausa-Georgian', $template);
        $this->assertStringContainsString('<option value="ha mr">', $template);
        $this->assertStringContainsString('Hausa-Marathi', $template);
        $this->assertStringContainsString('<option value="ha ms">', $template);
        $this->assertStringContainsString('Hausa-Malaysian', $template);
        $this->assertStringContainsString('<option value="ha pt">', $template);
        $this->assertStringContainsString('Hausa-Portuguese', $template);
        $this->assertStringContainsString('<option value="ha qu">', $template);
        $this->assertStringContainsString('Hausa-Quechua', $template);
        $this->assertStringContainsString('<option value="ha ro">', $template);
        $this->assertStringContainsString('Hausa-Romanian', $template);
        $this->assertStringContainsString('<option value="ha ru">', $template);
        $this->assertStringContainsString('Hausa-Russian', $template);
        $this->assertStringContainsString('<option value="ha tg">', $template);
        $this->assertStringContainsString('Hausa-Tajik', $template);
        $this->assertStringContainsString('<option value="ha tt">', $template);
        $this->assertStringContainsString('Hausa-Tatar', $template);
        $this->assertStringContainsString('<option value="ha yo">', $template);
        $this->assertStringContainsString('Hausa-Yoruba', $template);
        $this->assertStringContainsString('<option value="ha zh">', $template);
        $this->assertStringContainsString('Hausa-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------Hindi--------</option>', $template);
        $this->assertStringContainsString('<option value="hi en">', $template);
        $this->assertStringContainsString('Hindi-English', $template);
        $this->assertStringContainsString('<option value="hi ar">', $template);
        $this->assertStringContainsString('Hindi-Arabic', $template);
        $this->assertStringContainsString('<option value="hi de">', $template);
        $this->assertStringContainsString('Hindi-German', $template);
        $this->assertStringContainsString('<option value="hi el">', $template);
        $this->assertStringContainsString('Hindi-Greek', $template);
        $this->assertStringContainsString('<option value="hi es">', $template);
        $this->assertStringContainsString('Hindi-Spanish', $template);
        $this->assertStringContainsString('<option value="hi fa">', $template);
        $this->assertStringContainsString('Hindi-Farsi', $template);
        $this->assertStringContainsString('<option value="hi ha">', $template);
        $this->assertStringContainsString('Hindi-Hausa', $template);
        $this->assertStringContainsString('<option value="hi id">', $template);
        $this->assertStringContainsString('Hindi-Indonesian', $template);
        $this->assertStringContainsString('<option value="hi ig">', $template);
        $this->assertStringContainsString('Hindi-Igbo', $template);
        $this->assertStringContainsString('<option value="hi it">', $template);
        $this->assertStringContainsString('Hindi-Italian', $template);
        $this->assertStringContainsString('<option value="hi ka">', $template);
        $this->assertStringContainsString('Hindi-Georgian', $template);
        $this->assertStringContainsString('<option value="hi mr">', $template);
        $this->assertStringContainsString('Hindi-Marathi', $template);
        $this->assertStringContainsString('<option value="hi ms">', $template);
        $this->assertStringContainsString('Hindi-Malaysian', $template);
        $this->assertStringContainsString('<option value="hi pt">', $template);
        $this->assertStringContainsString('Hindi-Portuguese', $template);
        $this->assertStringContainsString('<option value="hi qu">', $template);
        $this->assertStringContainsString('Hindi-Quechua', $template);
        $this->assertStringContainsString('<option value="hi ro">', $template);
        $this->assertStringContainsString('Hindi-Romanian', $template);
        $this->assertStringContainsString('<option value="hi ru">', $template);
        $this->assertStringContainsString('Hindi-Russian', $template);
        $this->assertStringContainsString('<option value="hi tg">', $template);
        $this->assertStringContainsString('Hindi-Tajik', $template);
        $this->assertStringContainsString('<option value="hi tt">', $template);
        $this->assertStringContainsString('Hindi-Tatar', $template);
        $this->assertStringContainsString('<option value="hi yo">', $template);
        $this->assertStringContainsString('Hindi-Yoruba', $template);
        $this->assertStringContainsString('<option value="hi zh">', $template);
        $this->assertStringContainsString('Hindi-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------Indonesian--------</option>', $template);
        $this->assertStringContainsString('<option value="id en">', $template);
        $this->assertStringContainsString('Indonesian-English', $template);
        $this->assertStringContainsString('<option value="id ar">', $template);
        $this->assertStringContainsString('Indonesian-Arabic', $template);
        $this->assertStringContainsString('<option value="id de">', $template);
        $this->assertStringContainsString('Indonesian-German', $template);
        $this->assertStringContainsString('<option value="id el">', $template);
        $this->assertStringContainsString('Indonesian-Greek', $template);
        $this->assertStringContainsString('<option value="id es">', $template);
        $this->assertStringContainsString('Indonesian-Spanish', $template);
        $this->assertStringContainsString('<option value="id fa">', $template);
        $this->assertStringContainsString('Indonesian-Farsi', $template);
        $this->assertStringContainsString('<option value="id ha">', $template);
        $this->assertStringContainsString('Indonesian-Hausa', $template);
        $this->assertStringContainsString('<option value="id hi">', $template);
        $this->assertStringContainsString('Indonesian-Hindi', $template);
        $this->assertStringContainsString('<option value="id ig">', $template);
        $this->assertStringContainsString('Indonesian-Igbo', $template);
        $this->assertStringContainsString('<option value="id it">', $template);
        $this->assertStringContainsString('Indonesian-Italian', $template);
        $this->assertStringContainsString('<option value="id ka">', $template);
        $this->assertStringContainsString('Indonesian-Georgian', $template);
        $this->assertStringContainsString('<option value="id mr">', $template);
        $this->assertStringContainsString('Indonesian-Marathi', $template);
        $this->assertStringContainsString('<option value="id ms">', $template);
        $this->assertStringContainsString('Indonesian-Malaysian', $template);
        $this->assertStringContainsString('<option value="id pt">', $template);
        $this->assertStringContainsString('Indonesian-Portuguese', $template);
        $this->assertStringContainsString('<option value="id qu">', $template);
        $this->assertStringContainsString('Indonesian-Quechua', $template);
        $this->assertStringContainsString('<option value="id ro">', $template);
        $this->assertStringContainsString('Indonesian-Romanian', $template);
        $this->assertStringContainsString('<option value="id ru">', $template);
        $this->assertStringContainsString('Indonesian-Russian', $template);
        $this->assertStringContainsString('<option value="id tg">', $template);
        $this->assertStringContainsString('Indonesian-Tajik', $template);
        $this->assertStringContainsString('<option value="id tt">', $template);
        $this->assertStringContainsString('Indonesian-Tatar', $template);
        $this->assertStringContainsString('<option value="id yo">', $template);
        $this->assertStringContainsString('Indonesian-Yoruba', $template);
        $this->assertStringContainsString('<option value="id zh">', $template);
        $this->assertStringContainsString('Indonesian-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------Italian--------</option>', $template);
        $this->assertStringContainsString('<option value="it en">', $template);
        $this->assertStringContainsString('Italian-English', $template);
        $this->assertStringContainsString('<option value="it ar">', $template);
        $this->assertStringContainsString('Italian-Arabic', $template);
        $this->assertStringContainsString('<option value="it de">', $template);
        $this->assertStringContainsString('Italian-German', $template);
        $this->assertStringContainsString('<option value="it el">', $template);
        $this->assertStringContainsString('Italian-Greek', $template);
        $this->assertStringContainsString('<option value="it es">', $template);
        $this->assertStringContainsString('Italian-Spanish', $template);
        $this->assertStringContainsString('<option value="it fa">', $template);
        $this->assertStringContainsString('Italian-Farsi', $template);
        $this->assertStringContainsString('<option value="it ha">', $template);
        $this->assertStringContainsString('Italian-Hausa', $template);
        $this->assertStringContainsString('<option value="it hi">', $template);
        $this->assertStringContainsString('Italian-Hindi', $template);
        $this->assertStringContainsString('<option value="it id">', $template);
        $this->assertStringContainsString('Italian-Indonesian', $template);
        $this->assertStringContainsString('<option value="it ig">', $template);
        $this->assertStringContainsString('Italian-Igbo', $template);
        $this->assertStringContainsString('<option value="it ka">', $template);
        $this->assertStringContainsString('Italian-Georgian', $template);
        $this->assertStringContainsString('<option value="it mr">', $template);
        $this->assertStringContainsString('Italian-Marathi', $template);
        $this->assertStringContainsString('<option value="it ms">', $template);
        $this->assertStringContainsString('Italian-Malaysian', $template);
        $this->assertStringContainsString('<option value="it pt">', $template);
        $this->assertStringContainsString('Italian-Portuguese', $template);
        $this->assertStringContainsString('<option value="it qu"', $template);
        $this->assertStringContainsString('Italian-Quechua', $template);
        $this->assertStringContainsString('<option value="it ro">', $template);
        $this->assertStringContainsString('Italian-Romanian', $template);
        $this->assertStringContainsString('<option value="it ru">', $template);
        $this->assertStringContainsString('Italian-Russian', $template);
        $this->assertStringContainsString('<option value="it tg">', $template);
        $this->assertStringContainsString('Italian-Tajik', $template);
        $this->assertStringContainsString('<option value="it tt">', $template);
        $this->assertStringContainsString('Italian-Tatar', $template);
        $this->assertStringContainsString('<option value="it yo">', $template);
        $this->assertStringContainsString('Italian-Yoruba', $template);
        $this->assertStringContainsString('<option value="it zh">', $template);
        $this->assertStringContainsString('Italian-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------Marathi--------</option>', $template);
        $this->assertStringContainsString('Italian-English', $template);
        $this->assertStringContainsString('<option value="mr en">', $template);
        $this->assertStringContainsString('Marathi-English', $template);
        $this->assertStringContainsString('<option value="mr ar">', $template);
        $this->assertStringContainsString('Marathi-Arabic', $template);
        $this->assertStringContainsString('<option value="mr de">', $template);
        $this->assertStringContainsString('Marathi-German', $template);
        $this->assertStringContainsString('<option value="mr el">', $template);
        $this->assertStringContainsString('Marathi-Greek', $template);
        $this->assertStringContainsString('<option value="mr es">', $template);
        $this->assertStringContainsString('Marathi-Spanish', $template);
        $this->assertStringContainsString('<option value="mr fa">', $template);
        $this->assertStringContainsString('Marathi-Farsi', $template);
        $this->assertStringContainsString('<option value="mr ha">', $template);
        $this->assertStringContainsString('Marathi-Hausa', $template);
        $this->assertStringContainsString('<option value="mr hi">', $template);
        $this->assertStringContainsString('Marathi-Hindi', $template);
        $this->assertStringContainsString('<option value="mr id">', $template);
        $this->assertStringContainsString('Marathi-Indonesian', $template);
        $this->assertStringContainsString('<option value="mr ig">', $template);
        $this->assertStringContainsString('Marathi-Igbo', $template);
        $this->assertStringContainsString('<option value="mr it">', $template);
        $this->assertStringContainsString('Marathi-Italian', $template);
        $this->assertStringContainsString('<option value="mr ka">', $template);
        $this->assertStringContainsString('Marathi-Georgian', $template);
        $this->assertStringContainsString('<option value="mr ms">', $template);
        $this->assertStringContainsString('Marathi-Malaysian', $template);
        $this->assertStringContainsString('<option value="mr pt">', $template);
        $this->assertStringContainsString('Marathi-Portuguese', $template);
        $this->assertStringContainsString('<option value="mr qu">', $template);
        $this->assertStringContainsString('Marathi-Quechua', $template);
        $this->assertStringContainsString('<option value="mr ro">', $template);
        $this->assertStringContainsString('Marathi-Romanian', $template);
        $this->assertStringContainsString('<option value="mr ru">', $template);
        $this->assertStringContainsString('Marathi-Russian', $template);
        $this->assertStringContainsString('<option value="mr tg">', $template);
        $this->assertStringContainsString('Marathi-Tajik', $template);
        $this->assertStringContainsString('<option value="mr tt">', $template);
        $this->assertStringContainsString('Marathi-Tatar', $template);
        $this->assertStringContainsString('<option value="mr yo">', $template);
        $this->assertStringContainsString('Marathi-Yoruba', $template);
        $this->assertStringContainsString('<option value="mr zh">', $template);
        $this->assertStringContainsString('Marathi-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------Malaysian--------</option>', $template);
        $this->assertStringContainsString('<option value="ms en">', $template);
        $this->assertStringContainsString('Malaysian-English', $template);
        $this->assertStringContainsString('<option value="ms ar">', $template);
        $this->assertStringContainsString('Malaysian-Arabic', $template);
        $this->assertStringContainsString('<option value="ms de">', $template);
        $this->assertStringContainsString('Malaysian-German', $template);
        $this->assertStringContainsString('<option value="ms el">', $template);
        $this->assertStringContainsString('Malaysian-Greek', $template);
        $this->assertStringContainsString('<option value="ms es">', $template);
        $this->assertStringContainsString('Malaysian-Spanish', $template);
        $this->assertStringContainsString('<option value="ms fa">', $template);
        $this->assertStringContainsString('Malaysian-Farsi', $template);
        $this->assertStringContainsString('<option value="ms ha">', $template);
        $this->assertStringContainsString('Malaysian-Hausa', $template);
        $this->assertStringContainsString('<option value="ms hi">', $template);
        $this->assertStringContainsString('Malaysian-Hindi', $template);
        $this->assertStringContainsString('<option value="ms id">', $template);
        $this->assertStringContainsString('Malaysian-Indonesian', $template);
        $this->assertStringContainsString('<option value="ms ig">', $template);
        $this->assertStringContainsString('Malaysian-Igbo', $template);
        $this->assertStringContainsString('<option value="ms it">', $template);
        $this->assertStringContainsString('Malaysian-Italian', $template);
        $this->assertStringContainsString('<option value="ms ka">', $template);
        $this->assertStringContainsString('Malaysian-Georgian', $template);
        $this->assertStringContainsString('<option value="ms mr">', $template);
        $this->assertStringContainsString('Malaysian-Marathi', $template);
        $this->assertStringContainsString('<option value="ms pt">', $template);
        $this->assertStringContainsString('Malaysian-Portuguese', $template);
        $this->assertStringContainsString('<option value="ms qu">', $template);
        $this->assertStringContainsString('Malaysian-Quechua', $template);
        $this->assertStringContainsString('<option value="ms ro">', $template);
        $this->assertStringContainsString('Malaysian-Romanian', $template);
        $this->assertStringContainsString('<option value="ms ru">', $template);
        $this->assertStringContainsString('Malaysian-Russian', $template);
        $this->assertStringContainsString('<option value="ms tg">', $template);
        $this->assertStringContainsString('Malaysian-Tajik', $template);
        $this->assertStringContainsString('<option value="ms tt">', $template);
        $this->assertStringContainsString('Malaysian-Tatar', $template);
        $this->assertStringContainsString('<option value="ms yo">', $template);
        $this->assertStringContainsString('Malaysian-Yoruba', $template);
        $this->assertStringContainsString('<option value="ms zh">', $template);
        $this->assertStringContainsString('Malaysian-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------Portuguese--------</option>', $template);
        $this->assertStringContainsString('<option value="pt en">', $template);
        $this->assertStringContainsString('Portuguese-English', $template);
        $this->assertStringContainsString('<option value="pt ar">', $template);
        $this->assertStringContainsString('Portuguese-Arabic', $template);
        $this->assertStringContainsString('<option value="pt de">', $template);
        $this->assertStringContainsString('Portuguese-German', $template);
        $this->assertStringContainsString('<option value="pt el">', $template);
        $this->assertStringContainsString('Portuguese-Greek', $template);
        $this->assertStringContainsString('<option value="pt es">', $template);
        $this->assertStringContainsString('Portuguese-Spanish', $template);
        $this->assertStringContainsString('<option value="pt fa">', $template);
        $this->assertStringContainsString('Portuguese-Farsi', $template);
        $this->assertStringContainsString('<option value="pt ha">', $template);
        $this->assertStringContainsString('Portuguese-Hausa', $template);
        $this->assertStringContainsString('<option value="pt hi">', $template);
        $this->assertStringContainsString('Portuguese-Hindi', $template);
        $this->assertStringContainsString('<option value="pt id">', $template);
        $this->assertStringContainsString('Portuguese-Indonesian', $template);
        $this->assertStringContainsString('<option value="pt ig">', $template);
        $this->assertStringContainsString('Portuguese-Igbo', $template);
        $this->assertStringContainsString('<option value="pt it">', $template);
        $this->assertStringContainsString('Portuguese-Italian', $template);
        $this->assertStringContainsString('<option value="pt ka">', $template);
        $this->assertStringContainsString('Portuguese-Georgian', $template);
        $this->assertStringContainsString('<option value="pt mr">', $template);
        $this->assertStringContainsString('Portuguese-Marathi', $template);
        $this->assertStringContainsString('<option value="pt ms">', $template);
        $this->assertStringContainsString('Portuguese-Malaysian', $template);
        $this->assertStringContainsString('<option value="pt qu">', $template);
        $this->assertStringContainsString('Portuguese-Quechua', $template);
        $this->assertStringContainsString('<option value="pt ro">', $template);
        $this->assertStringContainsString('Portuguese-Romanian', $template);
        $this->assertStringContainsString('<option value="pt ru">', $template);
        $this->assertStringContainsString('Portuguese-Russian', $template);
        $this->assertStringContainsString('<option value="pt tg">', $template);
        $this->assertStringContainsString('Portuguese-Tajik', $template);
        $this->assertStringContainsString('<option value="pt tt">', $template);
        $this->assertStringContainsString('Portuguese-Tatar', $template);
        $this->assertStringContainsString('<option value="pt yo">', $template);
        $this->assertStringContainsString('Portuguese-Yoruba', $template);
        $this->assertStringContainsString('<option value="pt zh">', $template);
        $this->assertStringContainsString('Portuguese-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------Quechua--------</option>', $template);
        $this->assertStringContainsString('<option value="qu en">', $template);
        $this->assertStringContainsString('Quechua-English', $template);
        $this->assertStringContainsString('<option value="qu ar">', $template);
        $this->assertStringContainsString('Quechua-Arabic', $template);
        $this->assertStringContainsString('<option value="qu de">', $template);
        $this->assertStringContainsString('Quechua-German', $template);
        $this->assertStringContainsString('<option value="qu el">', $template);
        $this->assertStringContainsString('Quechua-Greek', $template);
        $this->assertStringContainsString('<option value="qu es">', $template);
        $this->assertStringContainsString('Quechua-Spanish', $template);
        $this->assertStringContainsString('<option value="qu fa">', $template);
        $this->assertStringContainsString('Quechua-Farsi', $template);
        $this->assertStringContainsString('<option value="qu ha">', $template);
        $this->assertStringContainsString('Quechua-Hausa', $template);
        $this->assertStringContainsString('<option value="qu hi">', $template);
        $this->assertStringContainsString('Quechua-Hindi', $template);
        $this->assertStringContainsString('<option value="qu id">', $template);
        $this->assertStringContainsString('Quechua-Indonesian', $template);
        $this->assertStringContainsString('<option value="qu ig">', $template);
        $this->assertStringContainsString('Quechua-Igbo', $template);
        $this->assertStringContainsString('<option value="qu it">', $template);
        $this->assertStringContainsString('Quechua-Italian', $template);
        $this->assertStringContainsString('<option value="qu ka">', $template);
        $this->assertStringContainsString('Quechua-Georgian', $template);
        $this->assertStringContainsString('<option value="qu mr">', $template);
        $this->assertStringContainsString('Quechua-Marathi', $template);
        $this->assertStringContainsString('<option value="qu ms">', $template);
        $this->assertStringContainsString('Quechua-Malaysian', $template);
        $this->assertStringContainsString('<option value="qu pt">', $template);
        $this->assertStringContainsString('Quechua-Portuguese', $template);
        $this->assertStringContainsString('<option value="qu ro">', $template);
        $this->assertStringContainsString('Quechua-Romanian', $template);
        $this->assertStringContainsString('<option value="qu ru">', $template);
        $this->assertStringContainsString('Quechua-Russian', $template);
        $this->assertStringContainsString('<option value="qu tg">', $template);
        $this->assertStringContainsString('Quechua-Tajik', $template);
        $this->assertStringContainsString('<option value="qu tt">', $template);
        $this->assertStringContainsString('Quechua-Tatar', $template);
        $this->assertStringContainsString('<option value="qu yo">', $template);
        $this->assertStringContainsString('Quechua-Yoruba', $template);
        $this->assertStringContainsString('<option value="qu zh">', $template);
        $this->assertStringContainsString('Quechua-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------Russian--------</option>', $template);
        $this->assertStringContainsString('<option value="ru en">', $template);
        $this->assertStringContainsString('Russian-English', $template);
        $this->assertStringContainsString('<option value="ru ar">', $template);
        $this->assertStringContainsString('Russian-Arabic', $template);
        $this->assertStringContainsString('<option value="ru de">', $template);
        $this->assertStringContainsString('Russian-German', $template);
        $this->assertStringContainsString('<option value="ru el">', $template);
        $this->assertStringContainsString('Russian-Greek', $template);
        $this->assertStringContainsString('<option value="ru es">', $template);
        $this->assertStringContainsString('Russian-Spanish', $template);
        $this->assertStringContainsString('<option value="ru fa">', $template);
        $this->assertStringContainsString('Russian-Farsi', $template);
        $this->assertStringContainsString('<option value="ru ha">', $template);
        $this->assertStringContainsString('Russian-Hausa', $template);
        $this->assertStringContainsString('<option value="ru hi">', $template);
        $this->assertStringContainsString('Russian-Hindi', $template);
        $this->assertStringContainsString('<option value="ru id">', $template);
        $this->assertStringContainsString('Russian-Indonesian', $template);
        $this->assertStringContainsString('<option value="ru ig">', $template);
        $this->assertStringContainsString('Russian-Igbo', $template);
        $this->assertStringContainsString('<option value="ru it">', $template);
        $this->assertStringContainsString('Russian-Italian', $template);
        $this->assertStringContainsString('<option value="ru ka">', $template);
        $this->assertStringContainsString('Russian-Georgian', $template);
        $this->assertStringContainsString('<option value="ru mr">', $template);
        $this->assertStringContainsString('Russian-Marathi', $template);
        $this->assertStringContainsString('<option value="ru ms">', $template);
        $this->assertStringContainsString('Russian-Malaysian', $template);
        $this->assertStringContainsString('<option value="ru pt">', $template);
        $this->assertStringContainsString('Russian-Portuguese', $template);
        $this->assertStringContainsString('<option value="ru qu">', $template);
        $this->assertStringContainsString('Russian-Quechua', $template);
        $this->assertStringContainsString('<option value="ru ro">', $template);
        $this->assertStringContainsString('Russian-Romanian', $template);
        $this->assertStringContainsString('<option value="ru tg">', $template);
        $this->assertStringContainsString('Russian-Tajik', $template);
        $this->assertStringContainsString('<option value="ru tt">', $template);
        $this->assertStringContainsString('Russian-Tatar', $template);
        $this->assertStringContainsString('<option value="ru yo">', $template);
        $this->assertStringContainsString('Russian-Yoruba', $template);
        $this->assertStringContainsString('<option value="ru zh">', $template);
        $this->assertStringContainsString('Russian-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------Telugu--------</option>', $template);
        $this->assertStringContainsString('<option value="te en">', $template);
        $this->assertStringContainsString('Telugu-English', $template);
        $this->assertStringContainsString('<option value="te ar">', $template);
        $this->assertStringContainsString('Telugu-Arabic', $template);
        $this->assertStringContainsString('<option value="te de">', $template);
        $this->assertStringContainsString('Telugu-German', $template);
        $this->assertStringContainsString('<option value="te el">', $template);
        $this->assertStringContainsString('Telugu-Greek', $template);
        $this->assertStringContainsString('<option value="te es">', $template);
        $this->assertStringContainsString('Telugu-Spanish', $template);
        $this->assertStringContainsString('<option value="te fa">', $template);
        $this->assertStringContainsString('Telugu-Farsi', $template);
        $this->assertStringContainsString('<option value="te ha">', $template);
        $this->assertStringContainsString('Telugu-Hausa', $template);
        $this->assertStringContainsString('<option value="te hi">', $template);
        $this->assertStringContainsString('Telugu-Hindi', $template);
        $this->assertStringContainsString('<option value="te id">', $template);
        $this->assertStringContainsString('Telugu-Indonesian', $template);
        $this->assertStringContainsString('<option value="te ig">', $template);
        $this->assertStringContainsString('Telugu-Igbo', $template);
        $this->assertStringContainsString('<option value="te it">', $template);
        $this->assertStringContainsString('Telugu-Italian', $template);
        $this->assertStringContainsString('<option value="te ka">', $template);
        $this->assertStringContainsString('Telugu-Georgian', $template);
        $this->assertStringContainsString('<option value="te mr">', $template);
        $this->assertStringContainsString('Telugu-Marathi', $template);
        $this->assertStringContainsString('<option value="te ms">', $template);
        $this->assertStringContainsString('Telugu-Malaysian', $template);
        $this->assertStringContainsString('<option value="te pt">', $template);
        $this->assertStringContainsString('Telugu-Portuguese', $template);
        $this->assertStringContainsString('<option value="te qu">', $template);
        $this->assertStringContainsString('Telugu-Quechua', $template);
        $this->assertStringContainsString('<option value="te ro">', $template);
        $this->assertStringContainsString('Telugu-Romanian', $template);
        $this->assertStringContainsString('<option value="te ru">', $template);
        $this->assertStringContainsString('Telugu-Russian', $template);
        $this->assertStringContainsString('<option value="te tg">', $template);
        $this->assertStringContainsString('Telugu-Tajik', $template);
        $this->assertStringContainsString('<option value="te tt">', $template);
        $this->assertStringContainsString('Telugu-Tatar', $template);
        $this->assertStringContainsString('<option value="te yo">', $template);
        $this->assertStringContainsString('Telugu-Yoruba', $template);
        $this->assertStringContainsString('<option value="te zh">', $template);
        $this->assertStringContainsString('Telugu-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------Tatar--------</option>', $template);
        $this->assertStringContainsString('<option value="tt en">', $template);
        $this->assertStringContainsString('Tatar-English', $template);
        $this->assertStringContainsString('<option value="tt ar">', $template);
        $this->assertStringContainsString('Tatar-Arabic', $template);
        $this->assertStringContainsString('<option value="tt de">', $template);
        $this->assertStringContainsString('Tatar-German', $template);
        $this->assertStringContainsString('<option value="tt el">', $template);
        $this->assertStringContainsString('Tatar-Greek', $template);
        $this->assertStringContainsString('<option value="tt es">', $template);
        $this->assertStringContainsString('Tatar-Spanish', $template);
        $this->assertStringContainsString('<option value="tt fa">', $template);
        $this->assertStringContainsString('Tatar-Farsi', $template);
        $this->assertStringContainsString('<option value="tt ha">', $template);
        $this->assertStringContainsString('Tatar-Hausa', $template);
        $this->assertStringContainsString('<option value="tt hi">', $template);
        $this->assertStringContainsString('Tatar-Hindi', $template);
        $this->assertStringContainsString('<option value="tt id">', $template);
        $this->assertStringContainsString('Tatar-Indonesian', $template);
        $this->assertStringContainsString('<option value="tt ig">', $template);
        $this->assertStringContainsString('Tatar-Igbo', $template);
        $this->assertStringContainsString('<option value="tt it">', $template);
        $this->assertStringContainsString('Tatar-Italian', $template);
        $this->assertStringContainsString('<option value="tt ka">', $template);
        $this->assertStringContainsString('Tatar-Georgian', $template);
        $this->assertStringContainsString('<option value="tt mr">', $template);
        $this->assertStringContainsString('Tatar-Marathi', $template);
        $this->assertStringContainsString('<option value="tt ms">', $template);
        $this->assertStringContainsString('Tatar-Malaysian', $template);
        $this->assertStringContainsString('<option value="tt pt">', $template);
        $this->assertStringContainsString('Tatar-Portuguese', $template);
        $this->assertStringContainsString('<option value="tt qu">', $template);
        $this->assertStringContainsString('Tatar-Quechua', $template);
        $this->assertStringContainsString('<option value="tt ro">', $template);
        $this->assertStringContainsString('Tatar-Romanian', $template);
        $this->assertStringContainsString('<option value="tt ru">', $template);
        $this->assertStringContainsString('Tatar-Russian', $template);
        $this->assertStringContainsString('<option value="tt tg">', $template);
        $this->assertStringContainsString('Tatar-Tajik', $template);
        $this->assertStringContainsString('<option value="tt yo">', $template);
        $this->assertStringContainsString('Tatar-Yoruba', $template);
        $this->assertStringContainsString('<option value="tt zh">', $template);
        $this->assertStringContainsString('Tatar-Chinese', $template);
        $this->assertStringContainsString('<option disabled>--------Chinese--------</option>', $template);
        $this->assertStringContainsString('<option value="zh en">', $template);
        $this->assertStringContainsString('Chinese-English', $template);
        $this->assertStringContainsString('<option value="zh ar">', $template);
        $this->assertStringContainsString('Chinese-Arabic', $template);
        $this->assertStringContainsString('<option value="zh de">', $template);
        $this->assertStringContainsString('Chinese-German', $template);
        $this->assertStringContainsString('<option value="zh el">', $template);
        $this->assertStringContainsString('Chinese-Greek', $template);
        $this->assertStringContainsString('<option value="zh es">', $template);
        $this->assertStringContainsString('Chinese-Spanish', $template);
        $this->assertStringContainsString('<option value="zh fa">', $template);
        $this->assertStringContainsString('Chinese-Farsi', $template);
        $this->assertStringContainsString('<option value="zh ha">', $template);
        $this->assertStringContainsString('Chinese-Hausa', $template);
        $this->assertStringContainsString('<option value="zh hi">', $template);
        $this->assertStringContainsString('Chinese-Hindi', $template);
        $this->assertStringContainsString('<option value="zh id">', $template);
        $this->assertStringContainsString('Chinese-Indonesian', $template);
        $this->assertStringContainsString('<option value="zh ig">', $template);
        $this->assertStringContainsString('Chinese-Igbo', $template);
        $this->assertStringContainsString('<option value="zh it">', $template);
        $this->assertStringContainsString('Chinese-Italian', $template);
        $this->assertStringContainsString('<option value="zh ka">', $template);
        $this->assertStringContainsString('Chinese-Georgian', $template);
        $this->assertStringContainsString('<option value="zh mr">', $template);
        $this->assertStringContainsString('Chinese-Marathi', $template);
        $this->assertStringContainsString('<option value="zh ms">', $template);
        $this->assertStringContainsString('Chinese-Malaysian', $template);
        $this->assertStringContainsString('<option value="zh pt">', $template);
        $this->assertStringContainsString('Chinese-Portuguese', $template);
        $this->assertStringContainsString('<option value="zh qu">', $template);
        $this->assertStringContainsString('Chinese-Quechua', $template);
        $this->assertStringContainsString('<option value="zh ro">', $template);
        $this->assertStringContainsString('Chinese-Romanian', $template);
        $this->assertStringContainsString('<option value="zh ru">', $template);
        $this->assertStringContainsString('Chinese-Russian', $template);
        $this->assertStringContainsString('<option value="zh tg">', $template);
        $this->assertStringContainsString('Chinese-Tajik', $template);
        $this->assertStringContainsString('<option value="zh tt">', $template);
        $this->assertStringContainsString('Chinese-Tatar', $template);
        $this->assertStringContainsString('<option value="zh yo">', $template);
        $this->assertStringContainsString('Chinese-Yoruba', $template);
    }
}
